version: "3"

services:
  cookbook:
    image: jekyll/jekyll
    restart: always
    container_name: cookbook
    command: jekyll serve -w
    working_dir: /srv/jekyll
    ports:
      - "80:4000"
    volumes:
      - .:/srv/jekyll
